### ISSUE TITLE
Add --version option

### ISSUE THREAD

**Issue by tseemann** [MDU-PHL/boobook#4]
Needed for proper audit trails.

```
% boobook --version
boobook 0.1
```

See also Issue #3

**Comment by andersgs** [comment]
Done. Now boobook --version prints the following:

> Version boobook:0.1.
> To get help, consult the github page: https://github.com/MDU-PHL/boobook
> boobook is distributed under GPLv3

**Comment by tseemann** [comment]
No - it has to be exactly as I show in the example. That is the GNU standard and is parseable.

**Comment by andersgs** [comment]
Done.

**Comment by andersgs** [comment]
Thank you, Torst.
